### ISSUE TITLE
[Improvements] Display inputs from resigned employees

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#305]
**Is your feature request related to a problem? Please describe.**
Do not remove the 3C's, Lessons Learnt, Action Items, Success Registers of resigned employees.

**Describe the solution you'd like**
Improvements data of resigned employees should remain visible

**Comment by GiannCarlo** [comment]
Fixed. Ready for Next build

**Comment by charissasylim** [comment]
@GiannCarlo  LL-10/01/19-06 of 220022462 (Rowena) is still not displaying in v.2.9.0.

**Comment by GiannCarlo** [comment]
@charissasylim , fixed na po ito now ma'am. Ready for next build.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0
