### ISSUE TITLE
[Daily Workplace Audit] Saving Daily Audit did not change Remarks and Status

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#576]
**Describe the bug**
Clicked Yes on every question in Check Daily Audit screen then clicked Save but it did nothing to the Daily Workplace Audit Remarks and Status for the day

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/82194503-80183380-9929-11ea-99ed-a8088d0aa7e3.png)
![image](https://user-images.githubusercontent.com/52391236/82194556-9625f400-9929-11ea-85fe-4be38c1a455e.png)

**Version (please complete the following information):**
 - Version 3.3.3

**Comment by chriscg** [comment]
This issue has been fixed by #579.

**Comment by charissasylim** [comment]
@trashvin @chriscg still not working in 3.3.4
@trashvin you can try it also since you are daily auditor for the week.

**Comment by GiannCarlo** [comment]
Hi Ms @charissasylim , this was handled by  #599_-_Workplace_Audit_-_able_to_save_/select_schedule_if_you_were_the_assigned_employee

PR contains 
 Workplace Audit -
  - Able to select schedule if you were the assigned employee,
  - Fixed bug when pressing others schedule and selecting different day/month/week/ will display blank schedule. 
 - Fixed remarks & Status when saving workplace audit.

I haven't merged it yet. I requested sir @chriscg  in the PR for review. :) hehe

**Comment by GiannCarlo** [comment]
Example : 
I updated the Friday Schedule in Daily Audit
![image](https://user-images.githubusercontent.com/28388078/83339288-de1c2200-a2fe-11ea-96ce-ebddbab55c86.png)

Then update it again ,
![image](https://user-images.githubusercontent.com/28388078/83339293-fc821d80-a2fe-11ea-8f02-2989e4a90554.png)

Status and Remarks has been updated.
